[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    esphome/ESPAsyncWebServer-esphome @ ^3.2.2
    bblanchon/ArduinoJson @ ^7.1.0
    miguelbalboa/MFRC522 @ ^1.4.11
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5
    adafruit/Adafruit INA219 @ ^1.2.3
